function get_output_node() { return array (
  'metrics' => 
  array (
    'Grid1' => 
    array (
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'SUM' => '0.000',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'MHz',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 's',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'SUM' => '0.000',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'CPUs',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'SUM' => '0.00',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'SUM' => '0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'SUM' => '0.0',
        'NUM' => '0',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'Grid2' => 
    array (
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'SUM' => '21.988',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '464',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'SUM' => '0.0',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'SUM' => '9976',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'MHz',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'SUM' => '5202633984',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 's',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'SUM' => '0.0',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'SUM' => '74.912',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'SUM' => '396.9',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'SUM' => '0.8',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'SUM' => '8257504',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'SUM' => '2022432',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'SUM' => '4',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'CPUs',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'SUM' => '482224',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'SUM' => '2.3',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'SUM' => '1',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'SUM' => '4107728',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'SUM' => '365.6',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'SUM' => '0.00',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'SUM' => '717248',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'SUM' => '0',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'SUM' => '8257504',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'SUM' => '283.6',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'c-1-2' => 
    array (
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'SUM' => '10.994',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '232',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'SUM' => '0.0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'SUM' => '4988',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'MHz',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'SUM' => '2601316992',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 's',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'SUM' => '0.0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'SUM' => '37.456',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'SUM' => '0.4',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'SUM' => '198.4',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'SUM' => '4128752',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'SUM' => '1011208',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'SUM' => '2',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'CPUs',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'SUM' => '241172',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'SUM' => '1.2',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'SUM' => '1',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'SUM' => '2053864',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'SUM' => '182.8',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'SUM' => '358644',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'SUM' => '0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'SUM' => '4128752',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'SUM' => '141.8',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'c-1-1' => 
    array (
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'SUM' => '10.994',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '232',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'SUM' => '0.0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'SUM' => '4988',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'MHz',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'SUM' => '2601316992',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 's',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'SUM' => '0.0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'SUM' => '37.456',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'SUM' => '0.5',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'SUM' => '198.3',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'SUM' => '4128752',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'packets/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'SUM' => '1011216',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'SUM' => '2',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'CPUs',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'SUM' => '241112',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'SUM' => '1.2',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'SUM' => '2',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'SUM' => '2053864',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'SUM' => '182.8',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'SUM' => '0.00',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'SUM' => '358624',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'SUM' => '0',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'SUM' => '4128752',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'KB',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'SUM' => '141.8',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => '%',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    '192.168.60.121' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:04',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.121',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'machine_type' => 
      array (
        'NAME' => 'machine_type',
        'VAL' => 'x86_64',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'VAL' => '5.497',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '116',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '372',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'gexec' => 
      array (
        'NAME' => 'gexec',
        'VAL' => 'OFF',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'VAL' => '2494',
        'TYPE' => 'uint32',
        'UNITS' => 'MHz',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'VAL' => '1300658496',
        'TYPE' => 'uint32',
        'UNITS' => 's',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_name' => 
      array (
        'NAME' => 'os_name',
        'VAL' => 'Linux',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '70',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_release' => 
      array (
        'NAME' => 'os_release',
        'VAL' => '2.6.18-164.el5',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'VAL' => '18.728',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'VAL' => '0.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'VAL' => '99.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'VAL' => '505600',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '325',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'VAL' => '1',
        'TYPE' => 'uint16',
        'UNITS' => 'CPUs',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'VAL' => '120616',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'VAL' => '0.6',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'VAL' => '0',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '372',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'VAL' => '1026932',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'VAL' => '91.4',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '3800',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'VAL' => '179332',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'VAL' => '0',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'VAL' => '70.9',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    '192.168.60.122' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:04',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.122',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'machine_type' => 
      array (
        'NAME' => 'machine_type',
        'VAL' => 'x86_64',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'VAL' => '5.497',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '116',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'gexec' => 
      array (
        'NAME' => 'gexec',
        'VAL' => 'OFF',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'VAL' => '2494',
        'TYPE' => 'uint32',
        'UNITS' => 'MHz',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'VAL' => '1300658496',
        'TYPE' => 'uint32',
        'UNITS' => 's',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_name' => 
      array (
        'NAME' => 'os_name',
        'VAL' => 'Linux',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '70',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_release' => 
      array (
        'NAME' => 'os_release',
        'VAL' => '2.6.18-164.el5',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'VAL' => '18.728',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'VAL' => '0.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'VAL' => '99.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'VAL' => '505608',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '325',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'VAL' => '1',
        'TYPE' => 'uint16',
        'UNITS' => 'CPUs',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'VAL' => '120556',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'VAL' => '0.6',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'VAL' => '1',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '292',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'VAL' => '1026932',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'VAL' => '91.4',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '252',
        'TMAX' => '3800',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '412',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'VAL' => '179312',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'VAL' => '0',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1012',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'VAL' => '70.9',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '292',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    '192.168.60.111' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:10',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.111',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'machine_type' => 
      array (
        'NAME' => 'machine_type',
        'VAL' => 'x86_64',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'VAL' => '5.497',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '116',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'gexec' => 
      array (
        'NAME' => 'gexec',
        'VAL' => 'OFF',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'VAL' => '2494',
        'TYPE' => 'uint32',
        'UNITS' => 'MHz',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'VAL' => '1300658496',
        'TYPE' => 'uint32',
        'UNITS' => 's',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_name' => 
      array (
        'NAME' => 'os_name',
        'VAL' => 'Linux',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '70',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_release' => 
      array (
        'NAME' => 'os_release',
        'VAL' => '2.6.18-164.el5',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'VAL' => '18.728',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'VAL' => '0.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'VAL' => '99.2',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'VAL' => '505608',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '325',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'VAL' => '1',
        'TYPE' => 'uint16',
        'UNITS' => 'CPUs',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'VAL' => '120556',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'VAL' => '0.6',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'VAL' => '1',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'VAL' => '1026932',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'VAL' => '91.4',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '3800',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'VAL' => '179312',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'VAL' => '0',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'VAL' => '70.9',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    '192.168.60.112' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:10',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.112',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'machine_type' => 
      array (
        'NAME' => 'machine_type',
        'VAL' => 'x86_64',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_free' => 
      array (
        'NAME' => 'disk_free',
        'VAL' => '5.497',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '116',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'gexec' => 
      array (
        'NAME' => 'gexec',
        'VAL' => 'OFF',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_nice' => 
      array (
        'NAME' => 'cpu_nice',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_in' => 
      array (
        'NAME' => 'pkts_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_speed' => 
      array (
        'NAME' => 'cpu_speed',
        'VAL' => '2494',
        'TYPE' => 'uint32',
        'UNITS' => 'MHz',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'boottime' => 
      array (
        'NAME' => 'boottime',
        'VAL' => '1300658496',
        'TYPE' => 'uint32',
        'UNITS' => 's',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_wio' => 
      array (
        'NAME' => 'cpu_wio',
        'VAL' => '0.0',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_name' => 
      array (
        'NAME' => 'os_name',
        'VAL' => 'Linux',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_one' => 
      array (
        'NAME' => 'load_one',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '70',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'os_release' => 
      array (
        'NAME' => 'os_release',
        'VAL' => '2.6.18-164.el5',
        'TYPE' => 'string',
        'UNITS' => '',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'disk_total' => 
      array (
        'NAME' => 'disk_total',
        'VAL' => '18.728',
        'TYPE' => 'double',
        'UNITS' => 'GB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_user' => 
      array (
        'NAME' => 'cpu_user',
        'VAL' => '0.3',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_idle' => 
      array (
        'NAME' => 'cpu_idle',
        'VAL' => '99.1',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_free' => 
      array (
        'NAME' => 'swap_free',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'pkts_out' => 
      array (
        'NAME' => 'pkts_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'packets/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_cached' => 
      array (
        'NAME' => 'mem_cached',
        'VAL' => '505608',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'load_five' => 
      array (
        'NAME' => 'load_five',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '325',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_num' => 
      array (
        'NAME' => 'cpu_num',
        'VAL' => '1',
        'TYPE' => 'uint16',
        'UNITS' => 'CPUs',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'load_fifteen' => 
      array (
        'NAME' => 'load_fifteen',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_free' => 
      array (
        'NAME' => 'mem_free',
        'VAL' => '120556',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'cpu_system' => 
      array (
        'NAME' => 'cpu_system',
        'VAL' => '0.6',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '90',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_run' => 
      array (
        'NAME' => 'proc_run',
        'VAL' => '1',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '286',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_total' => 
      array (
        'NAME' => 'mem_total',
        'VAL' => '1026932',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'cpu_aidle' => 
      array (
        'NAME' => 'cpu_aidle',
        'VAL' => '91.4',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '246',
        'TMAX' => '3800',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'bytes_in' => 
      array (
        'NAME' => 'bytes_in',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '406',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_buffers' => 
      array (
        'NAME' => 'mem_buffers',
        'VAL' => '179312',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'mem_shared' => 
      array (
        'NAME' => 'mem_shared',
        'VAL' => '0',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'swap_total' => 
      array (
        'NAME' => 'swap_total',
        'VAL' => '2064376',
        'TYPE' => 'float',
        'UNITS' => 'KB',
        'TN' => '1006',
        'TMAX' => '1200',
        'DMAX' => '0',
        'SLOPE' => 'zero',
        'SOURCE' => 'gmond',
      ),
      'part_max_used' => 
      array (
        'NAME' => 'part_max_used',
        'VAL' => '70.9',
        'TYPE' => 'float',
        'UNITS' => '%',
        'TN' => '286',
        'TMAX' => '180',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'disk_free' => 
    array (
      'NAME' => 'disk_free',
      'VAL' => '5.497',
      'TYPE' => 'double',
      'UNITS' => 'GB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'disk',
      ),
      'DESC' => 'Total free disk space',
      'TITLE' => 'Disk Space Available',
    ),
    'bytes_out' => 
    array (
      'NAME' => 'bytes_out',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => 'bytes/sec',
      'TN' => '406',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'network',
      ),
      'DESC' => 'Number of bytes out per second',
      'TITLE' => 'Bytes Sent',
    ),
    'proc_total' => 
    array (
      'NAME' => 'proc_total',
      'VAL' => '116',
      'TYPE' => 'uint32',
      'UNITS' => ' ',
      'TN' => '286',
      'TMAX' => '950',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'process',
      ),
      'DESC' => 'Total number of processes',
      'TITLE' => 'Total Processes',
    ),
    'pkts_in' => 
    array (
      'NAME' => 'pkts_in',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => 'packets/sec',
      'TN' => '406',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'network',
      ),
      'DESC' => 'Packets in per second',
      'TITLE' => 'Packets Received',
    ),
    'cpu_nice' => 
    array (
      'NAME' => 'cpu_nice',
      'VAL' => '0.0',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '90',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percentage of CPU utilization that occurred while executing at the user level with nice priority',
      'TITLE' => 'CPU Nice',
    ),
    'cpu_speed' => 
    array (
      'NAME' => 'cpu_speed',
      'VAL' => '2494',
      'TYPE' => 'uint32',
      'UNITS' => 'MHz',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'CPU Speed in terms of MHz',
      'TITLE' => 'CPU Speed',
    ),
    'boottime' => 
    array (
      'NAME' => 'boottime',
      'VAL' => '1300658496',
      'TYPE' => 'uint32',
      'UNITS' => 's',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'system',
      ),
      'DESC' => 'The last time that the system was started',
      'TITLE' => 'Last Boot Time',
    ),
    'cpu_wio' => 
    array (
      'NAME' => 'cpu_wio',
      'VAL' => '0.0',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '90',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percentage of time that the CPU or CPUs were idle during which the system had an outstanding disk I/O request',
      'TITLE' => 'CPU wio',
    ),
    'load_one' => 
    array (
      'NAME' => 'load_one',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => ' ',
      'TN' => '286',
      'TMAX' => '70',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'load',
      ),
      'DESC' => 'One minute load average',
      'TITLE' => 'One Minute Load Average',
    ),
    'disk_total' => 
    array (
      'NAME' => 'disk_total',
      'VAL' => '18.728',
      'TYPE' => 'double',
      'UNITS' => 'GB',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'disk',
      ),
      'DESC' => 'Total available disk space',
      'TITLE' => 'Total Disk Space',
    ),
    'cpu_idle' => 
    array (
      'NAME' => 'cpu_idle',
      'VAL' => '99.1',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '90',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percentage of time that the CPU or CPUs were idle and the system did not have an outstanding disk I/O request',
      'TITLE' => 'CPU Idle',
    ),
    'cpu_user' => 
    array (
      'NAME' => 'cpu_user',
      'VAL' => '0.3',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '90',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percentage of CPU utilization that occurred while executing at the user level',
      'TITLE' => 'CPU User',
    ),
    'swap_free' => 
    array (
      'NAME' => 'swap_free',
      'VAL' => '2064376',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Amount of available swap memory',
      'TITLE' => 'Free Swap Space',
    ),
    'mem_cached' => 
    array (
      'NAME' => 'mem_cached',
      'VAL' => '505608',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Amount of cached memory',
      'TITLE' => 'Cached Memory',
    ),
    'pkts_out' => 
    array (
      'NAME' => 'pkts_out',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => 'packets/sec',
      'TN' => '406',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'network',
      ),
      'DESC' => 'Packets out per second',
      'TITLE' => 'Packets Sent',
    ),
    'load_five' => 
    array (
      'NAME' => 'load_five',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => ' ',
      'TN' => '286',
      'TMAX' => '325',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'load',
      ),
      'DESC' => 'Five minute load average',
      'TITLE' => 'Five Minute Load Average',
    ),
    'cpu_num' => 
    array (
      'NAME' => 'cpu_num',
      'VAL' => '1',
      'TYPE' => 'uint16',
      'UNITS' => 'CPUs',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Total number of CPUs',
      'TITLE' => 'CPU Count',
    ),
    'load_fifteen' => 
    array (
      'NAME' => 'load_fifteen',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => ' ',
      'TN' => '286',
      'TMAX' => '950',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'load',
      ),
      'DESC' => 'Fifteen minute load average',
      'TITLE' => 'Fifteen Minute Load Average',
    ),
    'mem_free' => 
    array (
      'NAME' => 'mem_free',
      'VAL' => '120556',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Amount of available memory',
      'TITLE' => 'Free Memory',
    ),
    'cpu_system' => 
    array (
      'NAME' => 'cpu_system',
      'VAL' => '0.6',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '90',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percentage of CPU utilization that occurred while executing at the system level',
      'TITLE' => 'CPU System',
    ),
    'proc_run' => 
    array (
      'NAME' => 'proc_run',
      'VAL' => '1',
      'TYPE' => 'uint32',
      'UNITS' => ' ',
      'TN' => '286',
      'TMAX' => '950',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'process',
      ),
      'DESC' => 'Total number of running processes',
      'TITLE' => 'Total Running Processes',
    ),
    'mem_total' => 
    array (
      'NAME' => 'mem_total',
      'VAL' => '1026932',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Total amount of memory displayed in KBs',
      'TITLE' => 'Memory Total',
    ),
    'cpu_aidle' => 
    array (
      'NAME' => 'cpu_aidle',
      'VAL' => '91.4',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '246',
      'TMAX' => '3800',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'cpu',
      ),
      'DESC' => 'Percent of time since boot idle CPU',
      'TITLE' => 'CPU aidle',
    ),
    'bytes_in' => 
    array (
      'NAME' => 'bytes_in',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => 'bytes/sec',
      'TN' => '406',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'network',
      ),
      'DESC' => 'Number of bytes in per second',
      'TITLE' => 'Bytes Received',
    ),
    'mem_buffers' => 
    array (
      'NAME' => 'mem_buffers',
      'VAL' => '179312',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Amount of buffered memory',
      'TITLE' => 'Memory Buffers',
    ),
    'mem_shared' => 
    array (
      'NAME' => 'mem_shared',
      'VAL' => '0',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Amount of shared memory',
      'TITLE' => 'Shared Memory',
    ),
    'swap_total' => 
    array (
      'NAME' => 'swap_total',
      'VAL' => '2064376',
      'TYPE' => 'float',
      'UNITS' => 'KB',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'memory',
      ),
      'DESC' => 'Total amount of swap space displayed in KBs',
      'TITLE' => 'Swap Space Total',
    ),
    'part_max_used' => 
    array (
      'NAME' => 'part_max_used',
      'VAL' => '70.9',
      'TYPE' => 'float',
      'UNITS' => '%',
      'TN' => '286',
      'TMAX' => '180',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'disk',
      ),
      'DESC' => 'Maximum percent used for all partitions',
      'TITLE' => 'Maximum Disk Space Used',
    ),
    'machine_type' => 
    array (
      'NAME' => 'machine_type',
      'VAL' => 'x86_64',
      'TYPE' => 'string',
      'UNITS' => '',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'system',
      ),
      'DESC' => 'System architecture',
      'TITLE' => 'Machine Type',
    ),
    'gexec' => 
    array (
      'NAME' => 'gexec',
      'VAL' => 'OFF',
      'TYPE' => 'string',
      'UNITS' => '',
      'TN' => '406',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'core',
      ),
      'DESC' => 'gexec available',
      'TITLE' => 'Gexec Status',
    ),
    'os_name' => 
    array (
      'NAME' => 'os_name',
      'VAL' => 'Linux',
      'TYPE' => 'string',
      'UNITS' => '',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'system',
      ),
      'DESC' => 'Operating system name',
      'TITLE' => 'Operating System',
    ),
    'os_release' => 
    array (
      'NAME' => 'os_release',
      'VAL' => '2.6.18-164.el5',
      'TYPE' => 'string',
      'UNITS' => '',
      'TN' => '1006',
      'TMAX' => '1200',
      'DMAX' => '0',
      'SLOPE' => 'zero',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'system',
      ),
      'DESC' => 'Operating system release date',
      'TITLE' => 'Operating System Release',
    ),
  ),
  'grid' => 
  array (
    'NAME' => 'Grid2',
    'AUTHORITY' => 'http://rhel5-dev/ganglia/g2',
    'LOCALTIME' => '1300678698',
  ),
  'cluster' => 
  array (
    'NAME' => 'c-1-1',
    'LOCALTIME' => '1300678697',
    'OWNER' => 'unspecified',
    'LATLONG' => 'unspecified',
    'URL' => 'unspecified',
  ),
  'hosts_up' => 
  array (
  ),
  'hosts_down' => 
  array (
    'NAME' => '192.168.60.112',
    'IP' => '192.168.60.112',
    'REPORTED' => '1300678687',
    'TN' => '255',
    'TMAX' => '20',
    'DMAX' => '0',
    'LOCATION' => 'unspecified',
    'GMOND_STARTED' => '1300658571',
  ),
  'self' => 'Grid2',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
); }

