<?php
// Auto-generated by scripts/get_samples.php.

function meta_output() { return array (
  'grid' => 
  array (
    'grid1' => 
    array (
      'NAME' => 'grid1',
      'AUTHORITY' => 'http://rhel5-dev/ganglia/g1',
      'LOCALTIME' => '1300665415',
      'GRID' => 1,
      'HOSTS_UP' => '8',
      'HOSTS_DOWN' => '0',
    ),
    'grid2' => 
    array (
      'NAME' => 'grid2',
      'AUTHORITY' => 'http://rhel5-dev/ganglia/g2',
      'LOCALTIME' => '1300665403',
      'GRID' => 1,
      'HOSTS_UP' => '4',
      'HOSTS_DOWN' => '0',
    ),
    'cluster2' => 
    array (
      'NAME' => 'cluster2',
      'LOCALTIME' => '1300665407',
      'OWNER' => 'unspecified',
      'LATLONG' => 'unspecified',
      'URL' => 'unspecified',
      'CLUSTER' => 1,
      'HOSTS_UP' => '2',
      'HOSTS_DOWN' => '0',
    ),
    'cluster1' => 
    array (
      'NAME' => 'cluster1',
      'LOCALTIME' => '1300665410',
      'OWNER' => 'unspecified',
      'LATLONG' => 'unspecified',
      'URL' => 'unspecified',
      'CLUSTER' => 1,
      'HOSTS_UP' => '2',
      'HOSTS_DOWN' => '0',
    ),
  ),
  'cluster' => 
  array (
  ),
  'hosts_up' => 
  array (
  ),
  'hosts_down' => 
  array (
  ),
  'metrics' => 
  array (
    'grid1' => 
    array (
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '63.37',
        'NUM' => '8',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '944',
        'NUM' => '8',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'grid2' => 
    array (
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '33.80',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '472',
        'NUM' => '4',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'cluster2' => 
    array (
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '12.67',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '94',
        'NUM' => '1',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'cluster1' => 
    array (
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'SUM' => '16.90',
        'NUM' => '2',
        'TYPE' => 'double',
        'UNITS' => 'bytes/sec',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'SUM' => '94',
        'NUM' => '1',
        'TYPE' => 'double',
        'UNITS' => ' ',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
  ),
  'self' => 'grid1',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
  'index_array' => 
  array (
  ),
); }

function cluster_output() { return array (
  'grid' => 
  array (
    'NAME' => 'Grid1',
    'AUTHORITY' => 'http://rhel5-dev/ganglia/g1',
    'LOCALTIME' => '1300665165',
  ),
  'cluster' => 
  array (
    'NAME' => 'cluster1',
    'LOCALTIME' => '1300665155',
    'OWNER' => 'unspecified',
    'LATLONG' => 'unspecified',
    'URL' => 'unspecified',
    'HOSTS_UP' => 2,
  ),
  'hosts_up' => 
  array (
    'cluster1-host1' => 
    array (
      'NAME' => 'cluster1-host1',
      'IP' => '192.168.60.111',
      'REPORTED' => '1300665137',
      'TN' => '22',
      'TMAX' => '20',
      'DMAX' => '0',
      'LOCATION' => 'unspecified',
      'GMOND_STARTED' => '1300658571',
    ),
    'cluster1-host2' => 
    array (
      'NAME' => 'cluster1-host2',
      'IP' => '192.168.60.112',
      'REPORTED' => '1300665151',
      'TN' => '8',
      'TMAX' => '20',
      'DMAX' => '0',
      'LOCATION' => 'unspecified',
      'GMOND_STARTED' => '1300658571',
    ),
  ),
  'hosts_down' => 
  array (
  ),
  'metrics' => 
  array (
    'cluster1-host1' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:18',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.111',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '145',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '118',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '435',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
    'cluster1-host2' => 
    array (
      'gmond_started' => 
      array (
        'NAME' => 'GMOND_STARTED',
        'VAL' => '1300658571',
        'TYPE' => 'timestamp',
      ),
      'last_reported' => 
      array (
        'NAME' => 'REPORTED',
        'VAL' => '0 days, 0:00:04',
        'TYPE' => 'string',
      ),
      'ip_address' => 
      array (
        'NAME' => 'IP',
        'VAL' => '192.168.60.112',
        'TYPE' => 'string',
      ),
      'location' => 
      array (
        'NAME' => 'LOCATION',
        'VAL' => 'unspecified',
        'TYPE' => 'string',
      ),
      'bytes_out' => 
      array (
        'NAME' => 'bytes_out',
        'VAL' => '0.00',
        'TYPE' => 'float',
        'UNITS' => 'bytes/sec',
        'TN' => '145',
        'TMAX' => '300',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
      'proc_total' => 
      array (
        'NAME' => 'proc_total',
        'VAL' => '118',
        'TYPE' => 'uint32',
        'UNITS' => ' ',
        'TN' => '515',
        'TMAX' => '950',
        'DMAX' => '0',
        'SLOPE' => 'both',
        'SOURCE' => 'gmond',
      ),
    ),
  ),
  'self' => 'Grid1',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
  'index_array' => 
  array (
  ),
); }

function index_array_output() { return array (
  'grid' => 
  array (
    'NAME' => 'grid2',
    'AUTHORITY' => 'http://rhel5-dev/ganglia/g2',
    'LOCALTIME' => '1301365914',
  ),
  'cluster' => 
  array (
  ),
  'hosts_up' => 
  array (
  ),
  'hosts_down' => 
  array (
  ),
  'metrics' => 
  array (
  ),
  'self' => 'grid2',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
  'index_array' => 
  array (
    'cluster' => 
    array (
      'cluster2-host1' => 'cluster2',
      'cluster2-host2' => 'cluster2',
      'cluster1-host1' => 'cluster1',
      'cluster1-host2' => 'cluster1',
    ),
    'metrics' => 
    array (
      'bytes_out' => 
      array (
        0 => 'cluster2-host1',
        1 => 'cluster2-host2',
        2 => 'cluster1-host1',
        3 => 'cluster1-host2',
      ),
      'proc_total' => 
      array (
        0 => 'cluster2-host1',
        1 => 'cluster2-host2',
        2 => 'cluster1-host1',
        3 => 'cluster1-host2',
      ),
    ),
  ),
); }

function cluster_summary_output() { return array (
  'grid' => 
  array (
    'NAME' => 'grid1',
    'AUTHORITY' => 'http://rhel5-dev/ganglia/g1',
    'LOCALTIME' => '1300849902',
  ),
  'cluster' => 
  array (
    'NAME' => 'cluster1',
    'LOCALTIME' => '1300849893',
    'OWNER' => 'unspecified',
    'LATLONG' => 'unspecified',
    'URL' => 'unspecified',
    'HOSTS_UP' => '2',
    'HOSTS_DOWN' => '0',
  ),
  'hosts_up' => 
  array (
  ),
  'hosts_down' => 
  array (
  ),
  'metrics' => 
  array (
    'bytes_out' => 
    array (
      'NAME' => 'bytes_out',
      'SUM' => '886.16',
      'NUM' => '2',
      'TYPE' => 'double',
      'UNITS' => 'bytes/sec',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
    ),
    'proc_total' => 
    array (
      'NAME' => 'proc_total',
      'SUM' => '94',
      'NUM' => '1',
      'TYPE' => 'double',
      'UNITS' => ' ',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
    ),
  ),
  'self' => 'grid1',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
  'index_array' => 
  array (
  ),
); }

function node_output() { return array (
  'grid' => 
  array (
    'NAME' => 'grid1',
    'AUTHORITY' => 'http://rhel5-dev/ganglia/g1',
    'LOCALTIME' => '1300665311',
  ),
  'cluster' => 
  array (
    'NAME' => 'cluster1',
    'LOCALTIME' => '1300665304',
    'OWNER' => 'unspecified',
    'LATLONG' => 'unspecified',
    'URL' => 'unspecified',
  ),
  'hosts_up' => 
  array (
    'NAME' => 'cluster1-host1',
    'IP' => '192.168.60.111',
    'REPORTED' => '1300665297',
    'TN' => '11',
    'TMAX' => '20',
    'DMAX' => '0',
    'LOCATION' => 'unspecified',
    'GMOND_STARTED' => '1300658571',
  ),
  'hosts_down' => 
  array (
  ),
  'metrics' => 
  array (
    'bytes_out' => 
    array (
      'NAME' => 'bytes_out',
      'VAL' => '0.00',
      'TYPE' => 'float',
      'UNITS' => 'bytes/sec',
      'TN' => '145',
      'TMAX' => '300',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'network',
      ),
      'DESC' => 'Number of bytes out per second',
      'TITLE' => 'Bytes Sent',
    ),
    'proc_total' => 
    array (
      'NAME' => 'proc_total',
      'VAL' => '118',
      'TYPE' => 'uint32',
      'UNITS' => ' ',
      'TN' => '579',
      'TMAX' => '950',
      'DMAX' => '0',
      'SLOPE' => 'both',
      'SOURCE' => 'gmond',
      'GROUP' => 
      array (
        0 => 'process',
      ),
      'DESC' => 'Total number of processes',
      'TITLE' => 'Total Processes',
    ),
  ),
  'self' => 'grid1',
  'backend_component' => 
  array (
    'source' => 'gmetad',
    'version' => '3.1.7',
  ),
  'index_array' => 
  array (
  ),
); }

