<?php
/**
 * Query a gmetad server using ganglia.php.
 * Save output for 5 different contexts into arrays returned by 5 different functions.
 *   Ex: "meta" -> function meta_output() { return array(...); }
 * 
 * Functions are saved into expected-output.php, for use in building test assertions.
 * See LegacyGmetadTest.php for more details.
 */
require_once '/Users/alex/Code/alexdean-ganglia-misc/ganglia-web/functions.php';
require_once '/Users/alex/Code/alexdean-ganglia-misc/ganglia-web/ganglia.php';

function format($data,$depth=1){
  $out = "";
  if(is_array($data)) {
    foreach($data as $key=>$value) {
      
      $outval = $key=="NAME" ? "<metrics>" : $key;
      if(! in_array($key, array('VAL','TYPE','UNITS','TN','TMAX','DMAX','SLOPE','GROUP','SOURCE','DESC','TITLE') ) ) {
        $out .= str_repeat("-", $depth) . $outval . "\n";
        if(is_array($value) && $depth<=3) {
          $out .= format($value, $depth+1);
        }
      }
      
    }
  }
  return $out;
}

$content = "<?php\n// Auto-generated by scripts/get_samples.php.\n\n";
$hostname = "cluster1-host1";
$clustername = "cluster1";

$contexts = array("meta", "cluster", "index_array", "cluster-summary", "node");
foreach($contexts as $context) {
  $index_array = array();
  $error="";

  # Gives time in seconds to retrieve and parse XML tree. With subtree-
  # capable gmetad, should be very fast in all but the largest cluster configurations.
  $parsetime = 0;

  # 2key = "Source Name" / "NAME | AUTHORITY | HOSTS_UP ..." = Value.
  $grid = array();

  # 1Key = "NAME | LOCALTIME | HOSTS_UP | HOSTS_DOWN" = Value.
  $cluster = array();

  # 2Key = "Cluster Name / Host Name" ... Value = Array of Host Attributes
  $hosts_up = array();
  # 2Key = "Cluster Name / Host Name" ... Value = Array of Host Attributes
  $hosts_down = array();

  # Context dependant structure.
  $metrics = array();

  # The name of our local grid.
  $self = " ";

  # store gmond and/or gmetad version info
  $backend_component = array();
  
  
  $ok = Gmetad('localhost',8699);
  if(!$ok) {
    echo $error;
  }
  
  $out['grid'] = $grid;
  $out['cluster'] = $cluster;
  $out['hosts_up'] = $hosts_up;
  $out['hosts_down'] = $hosts_down;
  $out['metrics'] = $metrics;
  $out['self'] = $self;
  $out['backend_component'] = $backend_component;
  $out['index_array'] = $index_array;
  
  $keys = format($out);
  echo "*** $context ***\n";
  echo $keys . "\n";
  
  $function_name = $context.'_output';
  if($context=='cluster-summary') {
    // can't have hyphen in function name.
    $function_name = 'cluster_summary_output';
  }
  $content .= "function ${function_name}() { return ".var_export($out, true)."; }\n\n";
}

$dir = dirname(__FILE__);
file_put_contents("${dir}/expected_output.php", $content);

?>